# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsipr < Formula
  desc "Checks whether an IP address is in AWS ranges."
  homepage "https://github.com/yano3/awsipr"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yano3/awsipr/releases/download/v0.2.0/awsipr_darwin_arm64.zip"
      sha256 "b4b0ac8cda9c00283d7520999155ee37ac6a4e31b93a3c82f394ca7fb29e461e"

      def install
        bin.install "awsipr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yano3/awsipr/releases/download/v0.2.0/awsipr_darwin_amd64.zip"
      sha256 "3146cf0f5276677bc46e099551dc29a1f6149b84d63f49b8ffce63dd1442e709"

      def install
        bin.install "awsipr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yano3/awsipr/releases/download/v0.2.0/awsipr_linux_amd64.zip"
      sha256 "b88027c6bcb3524345a795903fa1c66990a0374dbe4e602ef35f278ba2d3a559"

      def install
        bin.install "awsipr"
      end
    end
  end
end
