builds:
  -
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  -
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
brews:
  -
    name: awsipr
    tap:
      owner: yano3
      name: homebrew-tap
    commit_author:
      name: Teppei Yano
      email: buckelwal@gmail.com
    homepage: https://github.com/yano3/awsipr
    description: Checks whether an IP address is in AWS ranges.
    license: MIT
